- hosts: TestServer

  become: yes

 

  tasks:

 

  - name: Installs nginx web server

 

    yum: 
    
        name: nginx 
        
        state: Installed 

        update_cache: true

 

    notify:

 

    - start nginx

 

  handlers:

 

  - name: start nginx

 

    service:

 

      name: nginx

 

      state: started
